[package]
name = "roguebench-protocol"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
roguebench-core.workspace = true
serde.workspace = true
