[package]
name = "roguebench-protocol"
description = "Network protocol and shared components for Roguebench"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
roguebench-core.workspace = true
bevy.workspace = true
serde.workspace = true
