[package]
name = "roguebench-client"
description = "Roguebench game client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "roguebench-client"
path = "src/main.rs"

[dependencies]
roguebench-engine.workspace = true
bevy.workspace = true
