[package]
name = "roguebench-storage"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
roguebench-core.workspace = true

# Database
rusqlite.workspace = true

# Utilities
uuid.workspace = true
thiserror.workspace = true
