[package]
name = "roguebench-server"
description = "Roguebench game server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "roguebench-server"
path = "src/main.rs"

[dependencies]
roguebench-engine.workspace = true
bevy.workspace = true
